/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author sajja
 */
public class ImageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ImageJPanel
     */
    public ImageJPanel() {
        initComponents();
        ImageIcon icon = new ImageIcon("C:\\Users\\sajja\\OneDrive\\Desktop\\images-Appl\\proj.jpg");
        Image img = icon.getImage();
        int width = 695;
        int height = 600;
        Image imgScale = img.getScaledInstance(width,height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jUser.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUser = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jUser.setMaximumSize(getPreferredSize());
        jUser.setMinimumSize(getPreferredSize());
        jUser.setPreferredSize(new java.awt.Dimension(695, 600));
        jUser.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jUserComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jUserComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jUserComponentResized
        // TODO add your handling code here:
  
   
    }//GEN-LAST:event_jUserComponentResized

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        jUser.setSize(this.getWidth(), this.getHeight());
        
        ImageIcon icon = new ImageIcon("C:\\Users\\sajja\\OneDrive\\Desktop\\images-Appl\\proj.jpg");
        Image img = icon.getImage();
        int width = this.getWidth();
        int height = this.getHeight();
        Image imgScale = img.getScaledInstance(width,height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jUser.setIcon(scaledIcon);
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jUser;
    // End of variables declaration//GEN-END:variables
}
